name: flutter_application_4
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  webview_flutter: ^3.0.4 # Versi terbaru

  get: 4.6.6

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

